In [1]:
import gradio as gr
import os
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras
from skimage import transform


C:\Users\Sharon\anaconda\envs\machine_learning\lib\site-packages\paramiko\transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [2]:

# Load the model from hugging spaces
# If this fails then load it from the local machine using keras.load()
# model=keras.models.load_model('./models/model5_random_over_sampling_precision')
from huggingface_hub.keras_mixin import from_pretrained_keras
m=from_pretrained_keras("2320sharon/Sniffer-Classifer")



config.json not found in HuggingFace Hub


In [3]:
new_model = tf.keras.models.load_model('model')
new_model.summary()
m=new_model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 498, 248, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 249, 124, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 247, 122, 32)      9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 123, 61, 32)      0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 121, 59, 32)       9248      
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 60, 29, 32)       0

In [4]:
image_path=r"C:\Users\Sharon\Downloads\ob-20220412T220737Z-001\ob"+os.sep+"2017-09-25-18-52-27_L8_rgbr.jpg"
img = keras.preprocessing.image.load_img(
    image_path, target_size=(500,250))
img_array = keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)  # Create batch axis
np.array(img_array) 
print(type(np.array(img_array) ))

<class 'numpy.ndarray'>


In [5]:
new_array=np.resize(img_array,(500, 250, 3))
new_array.shape

(500, 250, 3)

In [6]:
m.predict(np.array(img_array))

array([[1., 0.]], dtype=float32)

In [7]:
def call_model(img):
    print(type(img))
    print(img.shape)
    img=transform.resize(img,(500, 250, 3), preserve_range=True, clip=True)
    # Convert to numpy array
    print(img.shape)
    img= tf.expand_dims(img, 0)
    print(img.shape)
    prediction=m.predict(img)
    print(prediction)
    reverse_mapping={0:"good",1:"bad"}
#     prediction=prediction.flatten().argmax(axis=0)
    label=reverse_mapping[prediction.flatten().argmax(axis=0)]
    print(label)
    return label


demo = gr.Interface(call_model, gr.inputs.Image(shape=(200, 200)), outputs=gr.outputs.Textbox(type="str"))

if __name__ == "__main__":
    demo.launch(share=True)

Running on local URL:  http://127.0.0.1:7861/
Running on public URL: https://28094.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)


<class 'numpy.ndarray'>
(200, 200, 3)
(500, 250, 3)
(1, 500, 250, 3)
[[1. 0.]]
good
<class 'numpy.ndarray'>
(200, 200, 3)
(500, 250, 3)
(1, 500, 250, 3)
[[1. 0.]]
good
<class 'numpy.ndarray'>
(200, 200, 3)
(500, 250, 3)
(1, 500, 250, 3)
[[1. 0.]]
good
<class 'numpy.ndarray'>
(200, 200, 3)
(500, 250, 3)
(1, 500, 250, 3)
[[1. 0.]]
good
<class 'numpy.ndarray'>
(200, 200, 3)
(500, 250, 3)
(1, 500, 250, 3)
[[0. 1.]]
bad
<class 'numpy.ndarray'>
(200, 200, 3)
(500, 250, 3)
(1, 500, 250, 3)
[[1. 0.]]
good
